<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-UB6TGO0" failures="2" tests="2" name="Test with Firefox" time="11.295" errors="0" timestamp="2023-04-18T18:23:28 PDT">
  <testcase classname="extentreport.ExtentReport1" name="testLogin" time="1.164">
    <failure type="java.lang.AssertionError" message="expected [The password you?ve entered is incorrect. Forgot Password?] but found [The password you’ve entered is incorrect. Forgot Password?]">
      <![CDATA[java.lang.AssertionError: expected [The password you?ve entered is incorrect. Forgot Password?] but found [The password you’ve entered is incorrect. Forgot Password?]
at extentreport.ExtentReport1.testLogin(ExtentReport1.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testLogin -->
  <testcase classname="extentreport.ExtentReport2" name="testLogin1" time="0.654">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at extentreport.ExtentReport2.testLogin1(ExtentReport2.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testLogin1 -->
</testsuite> <!-- Test with Firefox -->
